services:
  kaabcloud-landing:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: kaabcloud-landing
    image: ghcr.io/jalejandrorp/kaabcloud-landing:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
